### ISSUE TITLE
coquille schema pour attribut d_service

### ISSUE THREAD

**Issue by fvanhoutte** [etalab/schema-stationnement-cyclable#12]
A vérifier mais coquille dans le schema pour l'attribut `d_service`
On parle de date en précisant format AAAA,, type entier mais en exemple on met 2020-02-27.
Soit on attend une année, soit une date année mois jour mais il faut faire suivre le type informatique

**Comment by NicolasBerthelot** [comment]
Bien vu. Merci beaucoup de l'avoir relévé.
Corrigé dans la prochaine version.
